name: Chocolatine
run-name: ${{github.actor}} checker chocolatine
on:
  push:
    branches:
      - '*'
      - 'ga-ignore-*'
  pull_request:
    branches:
      - '*'
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:zoltanbabko/chocolatine.git"
  EXECUTABLES: "fazzbizz"

jobs:
  check_coding_style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - id: check_coding_style
        name: Run coding-style
        run: check.sh . /tmp
      - run: |
          input=/tmp/coding-style-reports.log
          while IFS= read -r -a line; do
            fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
            echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
          done < $input
      - run: |
          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
          if [ $NB_ERROR -gt 0 ]; then
            echo Coding style error detected
            exit 1
          fi
    
  check_program_compilation:
    name: Check Program Compilation
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker:latest
    needs: check_coding_style
    steps:  
      - uses: actions/checkout@v3
      - id: check_program_compilation
        run: make
      - run: make clean 
      - run: |
          for file in ${{ env.EXECUTABLES }};do
            if [ ! -x "$file" ]; then
              echo "File $file not here or not executable"
              exit 1
            fi
          done

  run_tests:
    name: Runs tests
    needs: check_program_compilation
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - id: run_tests
        run: make tests_run

  push_to_mirror:
    name: Push To Mirror
    runs-on: ubuntu-latest
    needs:  run_tests
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        